{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-inventory-backend.fullname" . }}-postgres
  labels:
    {{- include "home-inventory-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: "Host={{ .Values.config.postgres.host }};Port={{ .Values.config.postgres.port }};Database={{ .Values.config.postgres.database }};Username={{ .Values.config.postgres.username }};Password={{ .Values.config.postgres.password }}"
{{- end }}
