// <auto-generated />
using System;
using HomeInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216215321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeInventory.Domain.Aggregates.CategoryAggregate.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("HomeInventory.Domain.Aggregates.InventoryItemAggregate.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_items_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_inventory_items_created_at");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("HomeInventory.Domain.Aggregates.InventoryItemAggregate.InventoryItem", b =>
                {
                    b.OwnsOne("HomeInventory.Domain.ValueObjects.FinancialInfo", "FinancialInfo", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("PurchaseDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("purchase_date");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("inventory_items");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");

                            b1.OwnsOne("HomeInventory.Domain.ValueObjects.Money", "CurrentValue", b2 =>
                                {
                                    b2.Property<Guid>("FinancialInfoInventoryItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("current_value_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("current_value_currency");

                                    b2.HasKey("FinancialInfoInventoryItemId");

                                    b2.ToTable("inventory_items");

                                    b2.WithOwner()
                                        .HasForeignKey("FinancialInfoInventoryItemId");
                                });

                            b1.OwnsOne("HomeInventory.Domain.ValueObjects.Money", "PurchasePrice", b2 =>
                                {
                                    b2.Property<Guid>("FinancialInfoInventoryItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("purchase_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("purchase_price_currency");

                                    b2.HasKey("FinancialInfoInventoryItemId");

                                    b2.ToTable("inventory_items");

                                    b2.WithOwner()
                                        .HasForeignKey("FinancialInfoInventoryItemId");
                                });

                            b1.Navigation("CurrentValue");

                            b1.Navigation("PurchasePrice");
                        });

                    b.OwnsOne("HomeInventory.Domain.ValueObjects.ItemBasicInfo", "BasicInfo", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("inventory_items");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.OwnsOne("HomeInventory.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Room")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("room");

                            b1.Property<string>("StorageSpot")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("storage_spot");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("inventory_items");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");

                            b1.OwnsOne("HomeInventory.Domain.ValueObjects.GpsCoordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationInventoryItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("gps_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("gps_longitude");

                                    b2.HasKey("LocationInventoryItemId");

                                    b2.ToTable("inventory_items");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationInventoryItemId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsMany("HomeInventory.Domain.ValueObjects.MediaReference", "Photos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long>("FileSizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size_bytes");

                            b1.Property<string>("FileUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("file_url");

                            b1.Property<string>("MediaType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("media_type");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.Property<Guid>("item_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("item_id");

                            b1.ToTable("item_photos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("item_id");
                        });

                    b.OwnsMany("HomeInventory.Domain.ValueObjects.MediaReference", "Receipts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long>("FileSizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size_bytes");

                            b1.Property<string>("FileUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("file_url");

                            b1.Property<string>("MediaType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("media_type");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.Property<Guid>("item_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("item_id");

                            b1.ToTable("item_receipts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("item_id");
                        });

                    b.OwnsMany("HomeInventory.Domain.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("item_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("tag_value");

                            b1.HasKey("item_id", "Value");

                            b1.ToTable("item_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("item_id");
                        });

                    b.Navigation("BasicInfo")
                        .IsRequired();

                    b.Navigation("FinancialInfo")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Photos");

                    b.Navigation("Receipts");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
