apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-inventory-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/filleellif/home-inventory.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: home-inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
